---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  # - name: ubuntu-14.04
  - name: centos-7.1
    driver_config:
      network:
      - ["forwarded_port", {guest: 443, host: 443, auto_correct: true}]

suites:
  - name: default
    run_list:
      - recipe[chef-compliance::default]
    attributes:
